### ISSUE TITLE
Can not Expand / Collapse Outline view with Keyboard

### ISSUE THREAD

**Issue by scottdensmore** [paxos/ghNotifier-issues#20]
I am trying to navigate with the Keyboard, yet the tree is never selected to allow me to expand or collapse. 

![2020-07-22 09 38 22](https://user-images.githubusercontent.com/125055/88203765-2a008e80-cbff-11ea-99cc-b2c36b57a636.gif)

**Comment by paxos** [comment]
Fixed in 0.31 (released today). Thanks for the feedback!
