### ISSUE TITLE
May be a user setting for how often app should sync

### ISSUE THREAD

**Issue by atkhalsa** [paxos/ghNotifier-issues#37]

**Comment by paxos** [comment]
Would you like to sync it more often or less often?

**Comment by cyberlionking** [comment]
what frequency is set now?

**Comment by atkhalsa** [comment]
what is the current frequency?

Nice to have and low priority

**Comment by paxos** [comment]
Its 60 seconds, which is the GitHub recommended value. Setting it higher would be helpful if someone runs into API limits.

**Comment by atkhalsa** [comment]
yeah I am looking into higher than that, but wanted a user to have a choice

**Comment by paxos** [comment]
👍 cool, gonna add a user setting for that
