### ISSUE TITLE
May be a setting in future to not sync during given time range "Silence Period", like at night

### ISSUE THREAD

**Issue by atkhalsa** [paxos/ghNotifier-issues#38]

**Comment by paxos** [comment]
As the app is using the system notifcations, that kind of exists already here:
<img width="780" alt="Screen Shot 2020-08-05 at 20 04 44" src="https://user-images.githubusercontent.com/121539/89486031-eeb1a400-d756-11ea-8f85-5b996a19f730.png">

It also respects the system Do not disturb setting here:
<img width="346" alt="Screen Shot 2020-08-05 at 20 06 02" src="https://user-images.githubusercontent.com/121539/89486097-1dc81580-d757-11ea-9687-1a9d2096265c.png">


However, I was planning to add a snooze setting for individual repos and maybe add a global notification on/off toggle in the app itself 🤔

**Comment by cyberlionking** [comment]
i was thinking about not syncing at night and not quitting app manually

**Comment by atkhalsa** [comment]
I was thinking about not syncing at night but don't want to quit app manually.

I already have system's Do Not Disturb enabled

This is a very low priority

**Comment by paxos** [comment]
Added a snooze button in v0.51.0 :+1:
<img width="700" alt="Screen Shot 2020-08-10 at 11 14 42" src="https://user-images.githubusercontent.com/121539/89767780-e3fe6280-dafa-11ea-9d59-6f8961472570.png">
